language: python
python: 2.7

services:
 - docker

env:
  - FILENAME=Dockerfile.ubuntu14.04
  - FILENAME=Dockerfile.ubuntu16.04
  - FILENAME=Dockerfile.ubuntu18.04
  - FILENAME=Dockerfile.debian8
  - FILENAME=Dockerfile.debian9

script:
- docker build -t ansible-docker -f $FILENAME .
